### PR TITLE
feat: allow h2, h3, h4 as values for header size

### PR DESCRIPTION
**Pull request by haakemon**

### CODE REVIEW

**Comment by haakemon** [comment]
Should not be merged until https://github.com/Altinn/altinn-studio/pull/7711 is merged

**Review by lorang92 — APPROVED** [review]

**Comment by haakemon** [comment]
@altinnadmin 
The feature PR is merged, so this can also be merged now.

**Comment by altinnadmin** [comment]
> The feature PR is merged, so this can also be merged now.

@haakemon Excellent! Done.

**Comment by ivarne** [comment]
Takk, ser frem til å oppdatere altinn2-convert

**Pull request merged**
